### ISSUE TITLE
[Feature Request] Standby verhindern

### ISSUE THREAD

**Issue by flames** [Jo2003/vlc_record#1]
Hallo Jörg,
wäre es möglich Ruhezustand/Bildschirmschoner/Monitor-Standby zu verhindern während vlc_record aktiv ist? Unter OS X 10.10.2 getestet, da schläft der Rechner ein, sowohl im Player als auch im Recorder (in meinem Fall Kratina.tv version).
Vielen Dank im Voraus
Gruss
Arthur

**Comment by Jo2003** [comment]
Hallo Arthur,
dieses Mac - Phänomen ist leider nicht so einfach zu fixen. Ich werde es mir trotzdem auf die Todo-Liste schreiben.
Es gibt aber einen - wie ich finde - guten Workaround. Es handelt sich dabei um das kleine Programm **Caffeine**. Mit diesem kleinen Tool kann man den Sleep-Modus des Mac sehr einfach beeinflussen.

[Caffeine im Mac App-Shop](https://itunes.apple.com/us/app/caffeine/id411246225)

**Comment by flames** [comment]
Heh, das nutze ich natürlich zur Zeit, aber die Frau kriegt's nicht auf die Reihe xD
Habe schon vermutet, dass es nur beim Mac auftritt, aber keine Gelegenheit gehabt es zu testen auf anderen Systemen.
Werde in der Freizeit auch mal reinschauen, falls was finde, gibts 'nen Pullrequest.
Überlegung wäre, da eh VLC Libs einbindest, den VLC Sleepblocker zu nutzen.

**Comment by Jo2003** [comment]
Na ja, eigentlich benutze ich schon die VLC Option "disable-screensaver". Schau mal in [cplayer.cpp:815](https://github.com/Jo2003/vlc_record/blob/master/cplayer.cpp#L815). 

Allerdings hat die benutzte Mac-Version vom VLC-Player auch schon etwas Patina angesetzt - ich habe bisher noch keine neue Version gefunden, die komplett funktioniert. Neuere Versionen hatten Probleme die Aspect-Ration bzw. den Crop zu ändern. Allerdings habe ich die 2.20 für den Mac noch nicht wirklich getestet.

**Comment by Jo2003** [comment]
Hallo Arthur,
ich habe mal versucht die bevorzugte Mac-Variante vom No-Sleep-Modus einzubauen. Das ganze verpackt in die neueste Vorschauversion von Kartina.TV:

[Download Vorschauversion](http://rt.coujo.de/kartina_tv-2.72.0-20150601-mac.dmg)

Für mehr Details siehe:

[macNoSleep.mm](https://github.com/Jo2003/vlc_record/blob/master/macNoSleep.mm)
[cplayer.cpp:21](https://github.com/Jo2003/vlc_record/blob/master/cplayer.cpp#L21)
und
[cplayer.cpp:1229-1322](https://github.com/Jo2003/vlc_record/blob/master/cplayer.cpp#L1219)

Gib bitte Bescheid, ob das Problem damit behoben ist!

Danke!

**Comment by Jo2003** [comment]
Hallo Arthur,

funktioniert denn die neue Version? 

Beste Grüße!

**Comment by flames** [comment]
Sorry für Abwesenheit, werde ich am Samstag unbedingt testen und Bescheid geben.

**Comment by flames** [comment]
Funktioniert perfekt, vielen Dank!

**Comment by Jo2003** [comment]
Sehr schön!
