### ISSUE TITLE
errors while building on ubuntu 

### ISSUE THREAD

**Issue by xxcriticxx** [Jo2003/vlc_record#6]
In file included from release/qrc_vlc-record.cpp:9:0:
release/qrc_vlc-record.cpp:2336:44: warning: ‘qInitResources_vlc_record__init_variable__’ defined but not used [-Wunused-variable]
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_vlc_record))
                                            ^
/usr/include/qt4/QtCore/qglobal.h:941:21: note: in definition of macro ‘Q_CONSTRUCTOR_FUNCTION0’
    static const int AFUNC ## __init_variable__ = AFUNC();
                     ^
release/qrc_vlc-record.cpp:2336:1: note: in expansion of macro ‘Q_CONSTRUCTOR_FUNCTION’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_vlc_record))
 ^
release/qrc_vlc-record.cpp:2336:24: note: in expansion of macro ‘QT_MANGLE_NAMESPACE’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_vlc_record))
                        ^
recorder.cpp:22:5: warning: #warning Channel List Times not given in GMT if timeshift is active! [-Wcpp]
    #warning Channel List Times not given in GMT if timeshift is active!
     ^
In file included from civiapi.cpp:18:0:
ivi_kartina_credits.h:26:2: warning: #warning Using defined values below will lead to not working IVI stuff! [-Wcpp]
 #warning Using defined values below will lead to not working IVI stuff!
  ^
In file included from release/qrc_lcd.cpp:9:0:
release/qrc_lcd.cpp:7030:44: warning: ‘qInitResources_lcd__init_variable__’ defined but not used [-Wunused-variable]
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_lcd))
                                            ^
/usr/include/qt4/QtCore/qglobal.h:941:21: note: in definition of macro ‘Q_CONSTRUCTOR_FUNCTION0’
    static const int AFUNC ## __init_variable__ = AFUNC();
                     ^
release/qrc_lcd.cpp:7030:1: note: in expansion of macro ‘Q_CONSTRUCTOR_FUNCTION’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_lcd))
 ^
release/qrc_lcd.cpp:7030:24: note: in expansion of macro ‘QT_MANGLE_NAMESPACE’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_lcd))
                        ^
In file included from release/qrc_common.cpp:9:0:
release/qrc_common.cpp:12966:44: warning: ‘qInitResources_common__init_variable__’ defined but not used [-Wunused-variable]
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_common))
                                            ^
/usr/include/qt4/QtCore/qglobal.h:941:21: note: in definition of macro ‘Q_CONSTRUCTOR_FUNCTION0’
    static const int AFUNC ## __init_variable__ = AFUNC();
                     ^
release/qrc_common.cpp:12966:1: note: in expansion of macro ‘Q_CONSTRUCTOR_FUNCTION’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_common))
 ^
release/qrc_common.cpp:12966:24: note: in expansion of macro ‘QT_MANGLE_NAMESPACE’
 Q_CONSTRUCTOR_FUNCTION(QT_MANGLE_NAMESPACE(qInitResources_common))

**Comment by xxcriticxx** [comment]
looking to build iptv1world.com variant for ubuntu 16.04

**Comment by Jo2003** [comment]
You have to compile it with qt4. Furthermore master branch will not work for your needs. I assume your service is a Rodnoe clone? If so, use branch Rodnoe.tv and build project iptv-record.pro

Best regards,
Jörg

**Comment by xxcriticxx** [comment]
@Jo2003 can you please provide guide or ready .deb file?

**Comment by Jo2003** [comment]
I can, when I'm home again. This will be on 24th of April.

**Comment by xxcriticxx** [comment]
@Jo2003 thx and happy travels

**Comment by xxcriticxx** [comment]
@Jo2003 anything on ubuntu builds?

**Comment by xxcriticxx** [comment]
@Jo2003 i installed deb file from my tv website but it auto closes. how can i correct this error?

**Comment by Jo2003** [comment]
@xxcriticxx You need it for i686 or x86_64? Will try to download current version from your provider.

**Comment by Jo2003** [comment]
@xxcriticxx I can't find a working site. Please send me a download link.

**Comment by xxcriticxx** [comment]
tv webiste

`https://polskatelewizjausa.com/index.php/jak-ogladac/ogladaj-na-komputerze`

![capture](https://cloud.githubusercontent.com/assets/15007183/25993032/9fe20384-36d6-11e7-9142-0243156bfa79.PNG)

link straight to the player

`https://ln.sync.com/dl/533d6cd50#qexbqqpk-vze2rmqg-u3hzyczn-cfgppqqe`

**Comment by xxcriticxx** [comment]
```
critic@critic:~$ uname -a
Linux critic 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
critic@critic:~$ cat /proc/version 
Linux version 4.4.0-75-generic (buildd@lgw01-21) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017
critic@critic:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by Jo2003** [comment]
That's the real error: iptv1world.com: error while loading shared libraries: libvlc.so.5: wrong ELF class: ELFCLASS64

**Comment by xxcriticxx** [comment]
build wrong?

**Comment by Jo2003** [comment]
You can download your version here:
http://www.filehosting.at/file/details/664829/iptv1world_2.69.4-20170512_amd64.deb

If it works a beer would be nice!

**Comment by xxcriticxx** [comment]
yes opens up now thank you i have to locate my password now :(

**Comment by xxcriticxx** [comment]
:beer:

**Comment by xxcriticxx** [comment]
i get this error when it opens but it works 

![screenshot from 2017-05-12 07-38-12](https://cloud.githubusercontent.com/assets/15007183/25996636/47bcddfe-36e6-11e7-9d9c-6506835b2dc6.png)

**Comment by Jo2003** [comment]
This is no error of the program, but an error of the update description file they host on their site.

**Comment by xxcriticxx** [comment]
so can this corrected? it comes up every time you open player

**Comment by Jo2003** [comment]
I can make a workaround for that. But this wouldn't be a fix. If you need a fix, ask them! They host an invalid update file. With the workaround I can make, you'll never get an update notification from them.

**Comment by xxcriticxx** [comment]
would the epg populate? because that's what the error is for. for example today is monday my epg opens up for wednesday when i open player.

**Comment by xxcriticxx** [comment]
fyi in regular player channels are counted down 1-100 for example. in linux version they go 1-10 then 1-5 there are broken down base on the categories

**Comment by Jo2003** [comment]
If the Windows version would be the same as the Linux version you'd see channels counting per group also on Windows. This is no bug, but a feature and was requested by the client.

**Comment by xxcriticxx** [comment]
On windows I see 1-100 something

**Comment by Jo2003** [comment]
As I told, if you would have exactly the same version for Windows as I gave you for Linux you also there would see channels counting per group.

**Comment by xxcriticxx** [comment]
Ok now I understand thank you

**Comment by jacwrob** [comment]
I've encountered the same problem. Unfortunately, the link to your build above is dead.
Can you share the build with me? (iptv1world_2.69.4-20170512_amd64.deb)
Thank you!
